#!/usr/bin/env python3
"""Ad-hoc plotter to compare PID output and DOB-compensated torque."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, Iterable, Tuple

import matplotlib.pyplot as plt
import numpy as np


def _load_csv(path: Path) -> Tuple[np.ndarray, Dict[str, np.ndarray]]:
    with path.open("r") as f:
        rows = [line for line in f if line.strip() and not line.startswith("#")]
    if not rows:
        raise ValueError(f"{path} has no data rows.")
    reader = csv.DictReader(rows)
    if not reader.fieldnames:
        raise ValueError(f"{path} does not define any header column.")
    columns: Dict[str, list[float]] = {name: [] for name in reader.fieldnames}
    for row in reader:
        for key, value in row.items():
            columns[key].append(float(value))
    series = {name: np.asarray(values, dtype=float) for name, values in columns.items()}
    time = series.get("time")
    if time is None:
        raise KeyError("CSV is missing required column 'time'.")
    return time, series


def _resolve(series: Dict[str, np.ndarray], names: Iterable[str]) -> Tuple[str, np.ndarray]:
    for name in names:
        if name in series:
            return name, series[name]
    raise KeyError(f"None of the columns {list(names)} exist in the CSV.")


def plot_tau_sources(csv_path: Path, save_path: Path | None = None, show: bool = False) -> Path:
    time, series = _load_csv(csv_path)
    pid_name, tau_pid = _resolve(series, ("tau_pid", "theta_ctrl"))
    dob_name, tau_dob = _resolve(series, ("tau_dob", "tau_out"))

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(time, tau_pid, label=f"{pid_name} (controller output)", color="tab:blue")
    ax.plot(time, tau_dob, label=f"{dob_name} (after DOB)", color="tab:orange")
    ax.set_xlabel("Time [s]")
    ax.set_ylabel("Torque [Nm]")
    ax.set_title("Torque contributions")
    ax.grid(True, alpha=0.2)
    ax.legend(loc="best")

    if save_path is None:
        target_dir = csv_path.parent / "fig"
        target_dir.mkdir(parents=True, exist_ok=True)
        save_path = target_dir / f"{csv_path.stem}_tau_sources.png"
    fig.tight_layout()
    fig.savefig(save_path, dpi=200)
    if show:
        plt.show()
    plt.close(fig)
    return save_path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Plot PID vs DOB torque traces from a controller CSV log."
    )
    parser.add_argument("csv_path", type=Path, help="Path to CSV log generated by the controller.")
    parser.add_argument("--save", type=Path, default=None, help="Optional output path for the plot.")
    parser.add_argument("--show", action="store_true", help="Display the plot interactively.")
    args = parser.parse_args()

    output_path = plot_tau_sources(args.csv_path, save_path=args.save, show=args.show)
    print(f"Saved torque comparison plot to {output_path}")


if __name__ == "__main__":
    main()
